---
name: WParkour
main: mcsim415\Parkour\Parkour
version: 1.1
api: [ 4.0.0 ]
author: World # = mcsim415
description: Parkour Plugin
mcpe-protocol: [527, 534, 544, 545] # 1.19 ~ 1.19.21
softdepend :
  - EconomyAPI

commands:
  parkour:
    description: Parkour command
    usage: "/parkour"
    permission: wparkour.command.parkour

permissions:
  wparkour.command.parkour:
    default: true
...
